"""Public test support for MasuGate providers and policy authors.

The backend-parameterization surface supports provider conformance tests over
PostgreSQL and SQLite.  The policy-author assertions compile and evaluate
policies against typed view stubs without requiring either database.
"""

from masugate.testing.backends import (
    Backend,
    BackendConn,
    PostgresBackend,
    SqliteBackend,
    available_backends,
)
from masugate.testing.faults import (
    FaultInjectingPostgresLedger,
    FaultPlan,
    FaultPoint,
    InjectedWorkerCrash,
)
from masugate.testing.policy import (
    PolicySource,
    StubView,
    StubViewResult,
    assert_allow,
    assert_deny,
    assert_escalate,
)
from masugate.testing.protected_execution import (
    BadFenceProbe,
    BadIdempotencyProbe,
    ExternalOperationDriftProbe,
    FalseFailureProbe,
    ProtectedExecutionConformanceError,
    ProtectedExecutionConformanceProbe,
    ProtectedExecutionConformanceReport,
    ReferenceProtectedConnector,
    ReferenceProtectedExecutionProbe,
    UnknownReleaseProbe,
    UnknownRetryProbe,
    conformance_authority,
    conformance_binding,
    run_protected_execution_conformance,
)
from masugate.testing.provider import (
    AuditCapture,
    BadWindowProviderProbe,
    CertifiedInputConformanceProbe,
    EffectExercise,
    EvaluationPointSample,
    ProviderConformanceError,
    ProviderConformanceProbe,
    ProviderConformanceReport,
    ProviderConformanceScenario,
    ReferenceProviderProbe,
    RequestTimeSample,
    ReservationExercise,
    StabilitySample,
    reference_conformance_scenario,
    run_certified_input_conformance,
    run_provider_conformance,
)

__all__ = [
    "AuditCapture",
    "Backend",
    "BackendConn",
    "BadFenceProbe",
    "BadIdempotencyProbe",
    "BadWindowProviderProbe",
    "CertifiedInputConformanceProbe",
    "EffectExercise",
    "EvaluationPointSample",
    "ExternalOperationDriftProbe",
    "FalseFailureProbe",
    "FaultInjectingPostgresLedger",
    "FaultPlan",
    "FaultPoint",
    "InjectedWorkerCrash",
    "PolicySource",
    "PostgresBackend",
    "ProtectedExecutionConformanceError",
    "ProtectedExecutionConformanceProbe",
    "ProtectedExecutionConformanceReport",
    "ProviderConformanceError",
    "ProviderConformanceProbe",
    "ProviderConformanceReport",
    "ProviderConformanceScenario",
    "ReferenceProtectedConnector",
    "ReferenceProtectedExecutionProbe",
    "ReferenceProviderProbe",
    "RequestTimeSample",
    "ReservationExercise",
    "SqliteBackend",
    "StabilitySample",
    "StubView",
    "StubViewResult",
    "UnknownReleaseProbe",
    "UnknownRetryProbe",
    "assert_allow",
    "assert_deny",
    "assert_escalate",
    "available_backends",
    "conformance_authority",
    "conformance_binding",
    "reference_conformance_scenario",
    "run_certified_input_conformance",
    "run_protected_execution_conformance",
    "run_provider_conformance",
]
