"""Framework-neutral governed tool runtime for MasuGate host adapters."""

from .conformance import (
    AdapterCoreConformanceClientFactory,
    AdapterCoreConformanceFixture,
    AdapterCoreConformanceReport,
    assert_adapter_core_conformance_canonical_bytes,
    create_adapter_core_conformance_runtime,
    load_adapter_core_conformance_fixture,
    run_adapter_core_conformance,
)
from .runtime import (
    AdapterCapabilities,
    AdapterCoreError,
    AdapterModelArgumentsError,
    ChangedInvocationConflictError,
    GovernedActionClient,
    GovernedLifecycle,
    GovernedRouteParser,
    GovernedToolRuntime,
    GovernedToolSpec,
    PendingLocatorMismatchError,
    PendingPresentation,
    TrustedInvocation,
    UnknownGovernedToolError,
    UnsupportedAdapterCapabilityError,
    classify_lifecycle,
)

__all__ = [
    "AdapterCapabilities",
    "AdapterCoreConformanceClientFactory",
    "AdapterCoreConformanceFixture",
    "AdapterCoreConformanceReport",
    "AdapterCoreError",
    "AdapterModelArgumentsError",
    "ChangedInvocationConflictError",
    "GovernedActionClient",
    "GovernedLifecycle",
    "GovernedRouteParser",
    "GovernedToolRuntime",
    "GovernedToolSpec",
    "PendingLocatorMismatchError",
    "PendingPresentation",
    "TrustedInvocation",
    "UnknownGovernedToolError",
    "UnsupportedAdapterCapabilityError",
    "assert_adapter_core_conformance_canonical_bytes",
    "classify_lifecycle",
    "create_adapter_core_conformance_runtime",
    "load_adapter_core_conformance_fixture",
    "run_adapter_core_conformance",
]
