"""Framework-neutral provider modules shipped with the MasuGate platform.

The modules in this package own policy state, durable provider transitions, and
their declared effect positions.  They deliberately do not import agent-host
configuration, identities, callbacks, or SDKs; a reference deployment binds
those concerns at its outer composition boundary.
"""

from masugate.providers.calendar import (
    CalendarError,
    CalendarPolicy,
    CalendarProvider,
    CalendarReservation,
    google_event_id,
)
from masugate.providers.certified_context import (
    CertifiedContextClock,
    CertifiedContextError,
    CertifiedContextPolicy,
    CertifiedContextProvider,
    CertifiedContextSource,
    ReferenceCertifiedContextSource,
    SqlSessionCertifiedClock,
)
from masugate.providers.communications import (
    ApprovalStateProvider,
    CommunicationClaim,
    CommunicationClaimConflict,
    CommunicationsError,
    CommunicationsPolicy,
    CommunicationsProvider,
    PolicyApprovalState,
)
from masugate.providers.customer_intent import CustomerIntentPolicy, CustomerIntentProvider
from masugate.providers.operational_limits import (
    OperationalLimitError,
    OperationalLimitExceeded,
    OperationalLimitReceipt,
    OperationalLimitsPolicy,
    OperationalLimitsProvider,
)
from masugate.providers.privacy_context import (
    ConsentMarketingRule,
    PhiRecipientRule,
    PiiClassifierConfig,
    PrivacyContextError,
    PrivacyContextPolicy,
    PrivacyContextProvider,
    PrivacyContextSource,
    PrivacyTransferRule,
    ReferencePrivacyContextSource,
)
from masugate.providers.regulatory_context import (
    ExportDestinationRule,
    PositionLimitRule,
    ReferenceRegulatoryContextSource,
    RegulatoryContextError,
    RegulatoryContextPolicy,
    RegulatoryContextProvider,
    RegulatoryContextSource,
    SanctionsCounterpartyRule,
    TradeWindowRule,
)
from masugate.providers.spend import (
    HttpReferencePurchaseApi,
    PostgresSpendOutboxStore,
    ReferencePurchaseApi,
    ReferencePurchaseConnector,
    ReferencePurchaseCredentialManifest,
    SpendEntitlement,
    SpendEntitlementState,
    SpendHandoff,
    SpendHandoffState,
    SpendOperation,
    SpendOperationStatus,
    SpendOutboxStore,
    SpendPolicy,
    SpendPolicyProvenance,
    SpendPurchaseRequest,
    SpendPurchaseService,
    SpendRecoveryError,
    SpendReservation,
    SpendResolution,
    SqliteReferencePurchaseApi,
    SqliteSpendOutboxStore,
    reference_purchase_binding_from_payload,
    reference_purchase_evidence_from_payload,
    reference_purchase_evidence_payload,
)

__all__ = [
    "ApprovalStateProvider",
    "CalendarError",
    "CalendarPolicy",
    "CalendarProvider",
    "CalendarReservation",
    "CertifiedContextClock",
    "CertifiedContextError",
    "CertifiedContextPolicy",
    "CertifiedContextProvider",
    "CertifiedContextSource",
    "CommunicationClaim",
    "CommunicationClaimConflict",
    "CommunicationsError",
    "CommunicationsPolicy",
    "CommunicationsProvider",
    "ConsentMarketingRule",
    "CustomerIntentPolicy",
    "CustomerIntentProvider",
    "ExportDestinationRule",
    "HttpReferencePurchaseApi",
    "OperationalLimitError",
    "OperationalLimitExceeded",
    "OperationalLimitReceipt",
    "OperationalLimitsPolicy",
    "OperationalLimitsProvider",
    "PhiRecipientRule",
    "PiiClassifierConfig",
    "PolicyApprovalState",
    "PositionLimitRule",
    "PostgresSpendOutboxStore",
    "PrivacyContextError",
    "PrivacyContextPolicy",
    "PrivacyContextProvider",
    "PrivacyContextSource",
    "PrivacyTransferRule",
    "ReferenceCertifiedContextSource",
    "ReferencePrivacyContextSource",
    "ReferencePurchaseApi",
    "ReferencePurchaseConnector",
    "ReferencePurchaseCredentialManifest",
    "ReferenceRegulatoryContextSource",
    "RegulatoryContextError",
    "RegulatoryContextPolicy",
    "RegulatoryContextProvider",
    "RegulatoryContextSource",
    "SanctionsCounterpartyRule",
    "SpendEntitlement",
    "SpendEntitlementState",
    "SpendHandoff",
    "SpendHandoffState",
    "SpendOperation",
    "SpendOperationStatus",
    "SpendOutboxStore",
    "SpendPolicy",
    "SpendPolicyProvenance",
    "SpendPurchaseRequest",
    "SpendPurchaseService",
    "SpendRecoveryError",
    "SpendReservation",
    "SpendResolution",
    "SqlSessionCertifiedClock",
    "SqliteReferencePurchaseApi",
    "SqliteSpendOutboxStore",
    "TradeWindowRule",
    "google_event_id",
    "reference_purchase_binding_from_payload",
    "reference_purchase_evidence_from_payload",
    "reference_purchase_evidence_payload",
]
